services:
  # PostgreSQL service
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24897
      POSTGRES_DB: user-service
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ port
      - '15672:15672' # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Redis service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  # NestJS user-service
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: user-service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development # Fixed typo
      - DATABASE_URL=postgres://postgres:24897@postgres:5432/user-service
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3000
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./src:/usr/src/app/src # Mount the whole project directory
volumes:
  postgres_data:
